/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Banking;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pavansomashekar
 */
public class BankJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankJPanel
     */
    private JPanel workJPanel;
    BankingJPanel bankingJPanel;
    FundingJPanel fundingJPanel;
    InsuranceJPanel insuranceJPanel;
    private String enterpriseName;
    
    public BankJPanel(JPanel workJPanel, String enterpriseName) {
        initComponents();
        this.workJPanel = workJPanel;
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bankJLabel = new javax.swing.JLabel();
        bankingJButton = new javax.swing.JButton();
        fundingJButton = new javax.swing.JButton();
        insuranceJButton = new javax.swing.JButton();

        bankJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        bankJLabel.setText("Bank");

        bankingJButton.setBackground(new java.awt.Color(204, 204, 0));
        bankingJButton.setText("Banking");
        bankingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankingJButtonActionPerformed(evt);
            }
        });

        fundingJButton.setBackground(new java.awt.Color(204, 204, 0));
        fundingJButton.setText("Funding");
        fundingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundingJButtonActionPerformed(evt);
            }
        });

        insuranceJButton.setBackground(new java.awt.Color(204, 204, 0));
        insuranceJButton.setText("Insurance");
        insuranceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fundingJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankingJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bankJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(bankJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(bankingJButton)
                .addGap(69, 69, 69)
                .addComponent(fundingJButton)
                .addGap(81, 81, 81)
                .addComponent(insuranceJButton)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fundingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundingJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        fundingJPanel = new FundingJPanel(workJPanel, enterpriseName);
        workJPanel.add("workArea", fundingJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_fundingJButtonActionPerformed

    private void insuranceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        insuranceJPanel = new InsuranceJPanel(workJPanel, enterpriseName);
        workJPanel.add("workArea", insuranceJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_insuranceJButtonActionPerformed

    private void bankingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankingJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        bankingJPanel = new BankingJPanel(workJPanel, enterpriseName);
        workJPanel.add("workArea", bankingJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_bankingJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bankJLabel;
    private javax.swing.JButton bankingJButton;
    private javax.swing.JButton fundingJButton;
    private javax.swing.JButton insuranceJButton;
    // End of variables declaration//GEN-END:variables
}
