/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pavansomashekar
 */
public class CustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerJPanel
     */
    
    private JPanel workJPanel;
    AccountInfoJPanel accountInfoJPanel;
    DepositJPanel depositJPanel;
    WithdrawJPanel withdrawJPanel;
    CardJPanel cardJPanel;
    LoanJPanel loanJPanel;
    
    public CustomerJPanel(JPanel workJPanel) {
        initComponents();
        this.workJPanel = workJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerJLabel = new javax.swing.JLabel();
        accInfoJButton = new javax.swing.JButton();
        depositJButton = new javax.swing.JButton();
        withdrawJButton = new javax.swing.JButton();
        cardsJButton = new javax.swing.JButton();
        loanJButton = new javax.swing.JButton();

        customerJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        customerJLabel.setText("Customer");

        accInfoJButton.setText("View Account Info");
        accInfoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accInfoJButtonActionPerformed(evt);
            }
        });

        depositJButton.setText("Deposit");
        depositJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositJButtonActionPerformed(evt);
            }
        });

        withdrawJButton.setText("Withdraw");
        withdrawJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawJButtonActionPerformed(evt);
            }
        });

        cardsJButton.setText("Creadit/Debit Cards");
        cardsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardsJButtonActionPerformed(evt);
            }
        });

        loanJButton.setText("Loan");
        loanJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(customerJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(235, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(depositJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loanJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardsJButton)
                            .addComponent(withdrawJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(customerJLabel)
                .addGap(77, 77, 77)
                .addComponent(accInfoJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(depositJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(withdrawJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(cardsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(loanJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accInfoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accInfoJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        accountInfoJPanel = new AccountInfoJPanel(workJPanel);
        workJPanel.add("workArea", accountInfoJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_accInfoJButtonActionPerformed

    private void depositJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        depositJPanel = new DepositJPanel(workJPanel);
        workJPanel.add("workArea", depositJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_depositJButtonActionPerformed

    private void withdrawJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        withdrawJPanel = new WithdrawJPanel(workJPanel);
        workJPanel.add("workArea", withdrawJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_withdrawJButtonActionPerformed

    private void cardsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardsJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        cardJPanel = new CardJPanel(workJPanel);
        workJPanel.add("workArea", cardJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_cardsJButtonActionPerformed

    private void loanJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        loanJPanel = new LoanJPanel(workJPanel);
        workJPanel.add("workArea", loanJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_loanJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accInfoJButton;
    private javax.swing.JButton cardsJButton;
    private javax.swing.JLabel customerJLabel;
    private javax.swing.JButton depositJButton;
    private javax.swing.JButton loanJButton;
    private javax.swing.JButton withdrawJButton;
    // End of variables declaration//GEN-END:variables
}
