/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Customer;

import Model.Customer;
import Model.Transaction;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pavansomashekar
 */
public class DepositJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DepositJPanel
     */
    
    private JPanel workJPanel;
    private String username;
    private int balance;
    
    Customer customer = new Customer();
    Transaction transaction = new Transaction();
    
    public DepositJPanel(JPanel workJPanel, String username) {
        initComponents();
        this.workJPanel = workJPanel;
        this.username = username;
        populateAccountBalance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        depositAmountJLabel = new javax.swing.JLabel();
        depositAmountJTextField = new javax.swing.JTextField();
        accountBalanceJLabel = new javax.swing.JLabel();
        depositJButton = new javax.swing.JButton();
        accountBalance = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        depositJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        depositJLabel.setText("Deposit");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        depositAmountJLabel.setBackground(new java.awt.Color(204, 204, 204));
        depositAmountJLabel.setText("Enter the amount to be deposited: ");

        depositAmountJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                depositAmountJTextFieldKeyPressed(evt);
            }
        });

        accountBalanceJLabel.setBackground(new java.awt.Color(204, 204, 204));
        accountBalanceJLabel.setText("Account Balance: ");

        depositJButton.setBackground(new java.awt.Color(0, 255, 0));
        depositJButton.setText("Deposit");
        depositJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositJButtonActionPerformed(evt);
            }
        });

        accountBalance.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depositAmountJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountBalanceJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depositAmountJTextField)
                            .addComponent(accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositJLabel)
                    .addComponent(depositJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(depositJLabel)
                .addGap(41, 41, 41)
                .addComponent(backJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountBalanceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAmountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(depositJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        workJPanel.remove(this);
        CardLayout layout = (CardLayout) workJPanel.getLayout();
        layout.previous(workJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void depositJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositJButtonActionPerformed
        // TODO add your handling code here:
        if(depositAmountJTextField.getText().equals((""))){
            JOptionPane.showMessageDialog(this, "Enter the amount to be deposited");
        }
        else{
            int depositAmount = Integer.parseInt(depositAmountJTextField.getText());
            int updatedBalance = balance+depositAmount;
            customer.updateAccountBalance(username, updatedBalance);
            transaction.addTransaction(username, "Credit", depositAmount, updatedBalance);
            JOptionPane.showMessageDialog(this, "Amount has been deposited");
            populateAccountBalance();
            depositAmountJTextField.setText("");
        }
        
    }//GEN-LAST:event_depositJButtonActionPerformed

    private void depositAmountJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositAmountJTextFieldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        String phNo = depositAmountJTextField.getText();
        int length = phNo.length();
        
        if(Character.isDigit(c)){
            if(length<10){
                depositAmountJTextField.setEditable(true);
            }
            else{
                depositAmountJTextField.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                depositAmountJTextField.setEditable(true);
            } 
            else{
                depositAmountJTextField.setEditable(false);
            }
        }
    }//GEN-LAST:event_depositAmountJTextFieldKeyPressed

    private void populateAccountBalance() {
        
        try{
            ResultSet rs = customer.getCustomerDetails(username);
            while(rs.next()){
                balance = Integer.parseInt(String.valueOf(rs.getString(7)));
                accountBalance.setText(String.valueOf(rs.getString(7)));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalance;
    private javax.swing.JLabel accountBalanceJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel depositAmountJLabel;
    private javax.swing.JTextField depositAmountJTextField;
    private javax.swing.JButton depositJButton;
    private javax.swing.JLabel depositJLabel;
    // End of variables declaration//GEN-END:variables
}
