/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Insurance;

import Model.Insurance;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pavansomashekar
 */
public class InsureAmountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsureAmountJPanel
     */
    private JPanel workJPanel;
    private String enterpriseName;
    
    Insurance insurance = new Insurance();
    
    public InsureAmountJPanel(JPanel workJPanel, String enterpriseName) {
        initComponents();
        this.workJPanel = workJPanel;
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insureJLabel = new javax.swing.JLabel();
        insuranceTypeJLabel = new javax.swing.JLabel();
        insuranceTypeJComboBox = new javax.swing.JComboBox<>();
        insuranceAmtJLabel = new javax.swing.JLabel();
        insuranceAmountJTextField = new javax.swing.JTextField();
        insureJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        insureJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        insureJLabel.setText("Insure");

        insuranceTypeJLabel.setText("Insurance Type");

        insuranceTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Life Insurance", "Home Insurance", "Health Insurance", "Car Insurance", "Bike Insurance" }));

        insuranceAmtJLabel.setText("Insurance Amount");

        insureJButton.setBackground(new java.awt.Color(0, 255, 0));
        insureJButton.setText("Insure");
        insureJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insureJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insuranceAmtJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insuranceTypeJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insuranceTypeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insuranceAmountJTextField))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insureJButton)
                    .addComponent(insureJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(insureJLabel)
                .addGap(39, 39, 39)
                .addComponent(backJButton)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceTypeJLabel)
                    .addComponent(insuranceTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceAmtJLabel)
                    .addComponent(insuranceAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(insureJButton)
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insureJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insureJButtonActionPerformed
        // TODO add your handling code here:
        if(insuranceAmountJTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter the insurance amount");
        }
        else{
            String insuranceType = (String) insuranceTypeJComboBox.getSelectedItem();
            int insuranceAmount = Integer.parseInt(insuranceAmountJTextField.getText());
            Random r = new Random();
            int insuranceId = 10000 + r.nextInt(10000);
            
            insurance.requestInsurance(enterpriseName, insuranceId, insuranceType, insuranceAmount);
        
            JOptionPane.showMessageDialog(this, "Insurance request sent");

            insuranceAmountJTextField.setText("");
        }
    }//GEN-LAST:event_insureJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        workJPanel.remove(this);
        CardLayout layout = (CardLayout) workJPanel.getLayout();
        layout.previous(workJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField insuranceAmountJTextField;
    private javax.swing.JLabel insuranceAmtJLabel;
    private javax.swing.JComboBox<String> insuranceTypeJComboBox;
    private javax.swing.JLabel insuranceTypeJLabel;
    private javax.swing.JButton insureJButton;
    private javax.swing.JLabel insureJLabel;
    // End of variables declaration//GEN-END:variables
}
