/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pavansomashekar
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    private JPanel workJPanel;
//    Connection conn;
    ManageNetworkJPanel manageNetworkJPanel;
    ManageEnterpriseJPanel manageEnterpriseJPanel;
    
    public AdminJPanel(JPanel workJPanel) {
        initComponents();
        this.workJPanel = workJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminJLabel = new javax.swing.JLabel();
        networkButton = new javax.swing.JButton();
        enterpriseButton = new javax.swing.JButton();

        adminJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        adminJLabel.setText("Admin");

        networkButton.setText("Manage Network");
        networkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkButtonActionPerformed(evt);
            }
        });

        enterpriseButton.setText("Manage Enterprise");
        enterpriseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(adminJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(networkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(enterpriseButton)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(adminJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkButton)
                    .addComponent(enterpriseButton))
                .addContainerGap(317, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void networkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkButtonActionPerformed
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        manageNetworkJPanel = new ManageNetworkJPanel(workJPanel);
        workJPanel.add("workArea", manageNetworkJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_networkButtonActionPerformed

    private void enterpriseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        manageEnterpriseJPanel = new ManageEnterpriseJPanel(workJPanel);
        workJPanel.add("workArea", manageEnterpriseJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_enterpriseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminJLabel;
    private javax.swing.JButton enterpriseButton;
    private javax.swing.JButton networkButton;
    // End of variables declaration//GEN-END:variables
}
