/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NGO;

import Model.NGO;
import Model.NGODirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author pavansomashekar
 */
public class NGOJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOJPanel
     */
    private JPanel workJPanel;
    private String enterpriseName;
    NGODirectory ngo = new NGODirectory();
    RequestFundsJPanel requestFundsJPanel;
    
    public NGOJPanel(JPanel workJPanel, String enterpriseName) {
        initComponents();
        this.workJPanel = workJPanel;
        this.enterpriseName = enterpriseName;
        JTableHeader thead = ngoJTable.getTableHeader();
        thead.setForeground(Color.BLUE);
        thead.setFont(thead.getFont().deriveFont(Font.BOLD));
        populateNGOTable();
        populateFundsAvailable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ngoJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ngoJTable = new javax.swing.JTable();
        fundsAvailableJLabel = new javax.swing.JLabel();
        availableFunds = new javax.swing.JLabel();
        requestFundsJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();

        ngoJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        ngoJLabel.setText("NGO");

        ngoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bank", "Reason", "Funds Requested", "Status"
            }
        ));
        jScrollPane1.setViewportView(ngoJTable);

        fundsAvailableJLabel.setText("Funds Available");

        requestFundsJButton.setBackground(new java.awt.Color(0, 255, 0));
        requestFundsJButton.setText("Request Funds");
        requestFundsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestFundsJButtonActionPerformed(evt);
            }
        });

        refreshJButton.setBackground(new java.awt.Color(204, 204, 0));
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(ngoJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshJButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fundsAvailableJLabel)
                .addGap(44, 44, 44)
                .addComponent(availableFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(requestFundsJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ngoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(refreshJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fundsAvailableJLabel)
                    .addComponent(availableFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(requestFundsJButton)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestFundsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestFundsJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)workJPanel.getLayout();
        requestFundsJPanel = new RequestFundsJPanel(workJPanel, enterpriseName);
        workJPanel.add("workArea", requestFundsJPanel);
        layout.next(workJPanel);
    }//GEN-LAST:event_requestFundsJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateNGOTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void populateNGOTable() {
        DefaultTableModel model = (DefaultTableModel) ngoJTable.getModel();

        model.setRowCount(0);
        
        try{
            ResultSet rs = ngo.getFundsRequested(enterpriseName);
            while(rs.next()){
            Object[] rows = new Object[4];
            rows[0]= rs.getString(2);
            rows[1]= rs.getString(3);
            rows[2]= rs.getString(4);
            rows[3]= rs.getString(5);
            model.addRow(rows);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
    private void populateFundsAvailable(){
        try{
            ResultSet rs = ngo.getFundsAvailable(enterpriseName);
            while(rs.next()){
                availableFunds.setText(String.valueOf(rs.getInt(1)));
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableFunds;
    private javax.swing.JLabel fundsAvailableJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ngoJLabel;
    private javax.swing.JTable ngoJTable;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton requestFundsJButton;
    // End of variables declaration//GEN-END:variables
}
