/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NGO;

import Model.NGO;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pavansomashekar
 */
public class RequestFundsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestFundsJPanel
     */
    private JPanel workJPanel;
    private String enterpriseName;
    NGO ngo = new NGO();
    
    public RequestFundsJPanel(JPanel workJPanel, String enterpriseName) {
        initComponents();
        this.workJPanel = workJPanel;
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestFundsJLabel = new javax.swing.JLabel();
        amountJLabel = new javax.swing.JLabel();
        amountJTextField = new javax.swing.JTextField();
        requestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        reasonJLabel = new javax.swing.JLabel();
        reasonJTextField = new javax.swing.JTextField();

        requestFundsJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        requestFundsJLabel.setText("Request Funds");

        amountJLabel.setText("Enter the amount");

        amountJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountJTextFieldKeyPressed(evt);
            }
        });

        requestJButton.setBackground(new java.awt.Color(0, 255, 0));
        requestJButton.setText("Request Funds");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        reasonJLabel.setText("Enter the reason");

        reasonJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reasonJTextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(requestFundsJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(reasonJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reasonJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(amountJTextField))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(requestJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(requestFundsJLabel)
                .addGap(46, 46, 46)
                .addComponent(backJButton)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reasonJLabel)
                    .addComponent(reasonJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountJLabel)
                    .addComponent(amountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(requestJButton)
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        workJPanel.remove(this);
        CardLayout layout = (CardLayout) workJPanel.getLayout();
        layout.previous(workJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
        if(reasonJTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter the reason");
        }
        else if(amountJTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter the amount");
        }
        else{
            int fundsRequested = Integer.parseInt(amountJTextField.getText());
            ngo.requestFunds(enterpriseName, reasonJTextField.getText(), fundsRequested);
            
            JOptionPane.showMessageDialog(this, "Funds request sent");

            reasonJTextField.setText("");
            amountJTextField.setText("");
        }
    }//GEN-LAST:event_requestJButtonActionPerformed

    private void amountJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountJTextFieldKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        String phNo = amountJTextField.getText();
        int length = phNo.length();
        
        if(Character.isDigit(c)){
            if(length<10){
                amountJTextField.setEditable(true);
            }
            else{
                amountJTextField.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                amountJTextField.setEditable(true);
            } 
            else{
                amountJTextField.setEditable(false);
            }
        }
    }//GEN-LAST:event_amountJTextFieldKeyPressed

    private void reasonJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reasonJTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonJTextFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountJLabel;
    private javax.swing.JTextField amountJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel reasonJLabel;
    private javax.swing.JTextField reasonJTextField;
    private javax.swing.JLabel requestFundsJLabel;
    private javax.swing.JButton requestJButton;
    // End of variables declaration//GEN-END:variables
}
